//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WhatExec.Cli.Localizations {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WhatExec.Cli.Localizations.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Took {0}ms to get results.
        /// </summary>
        internal static string Commands_Results_ReportTime_Milliseconds {
            get {
                return ResourceManager.GetString("Commands.Results.ReportTime.Milliseconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: No commands or executables were specified..
        /// </summary>
        internal static string Errors_Commands_NoCommandsSpecified {
            get {
                return ResourceManager.GetString("Errors.Commands.NoCommandsSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: Could not resolve the specified command(s) or executable(s): {x}.
        /// </summary>
        internal static string Errors_Results_CommandsNotFound {
            get {
                return ResourceManager.GetString("Errors.Results.CommandsNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Limit must be greater than or equal to 1..
        /// </summary>
        internal static string Exceptions_Commands_Find_Limit_MustBeGreaterThanZero {
            get {
                return ResourceManager.GetString("Exceptions.Commands.Find.Limit.MustBeGreaterThanZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not locate the specified drive {0}..
        /// </summary>
        internal static string Exceptions_DriveNotFound {
            get {
                return ResourceManager.GetString("Exceptions.DriveNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information: Couldn&apos;t find command(s) or executable(s): {0}.
        /// </summary>
        internal static string Information_Results_CommandsNotFound {
            get {
                return ResourceManager.GetString("Information.Results.CommandsNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like to enter another command to search for?.
        /// </summary>
        internal static string Prompts_CommandInput_AddAnother {
            get {
                return ResourceManager.GetString("Prompts.CommandInput.AddAnother", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One or more executables could not be located. Do you want to continue resolving the remaining executables?.
        /// </summary>
        internal static string Prompts_Errors_ContinueAfterError {
            get {
                return ResourceManager.GetString("Prompts.Errors.ContinueAfterError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directory.
        /// </summary>
        internal static string Prompts_Highlights_Directory {
            get {
                return ResourceManager.GetString("Prompts.Highlights.Directory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to search.
        /// </summary>
        internal static string Prompts_Highlights_Search {
            get {
                return ResourceManager.GetString("Prompts.Highlights.Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Storage Drive.
        /// </summary>
        internal static string Prompts_Highlights_StorageDrive {
            get {
                return ResourceManager.GetString("Prompts.Highlights.StorageDrive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select the Directory to search for the executable/command..
        /// </summary>
        internal static string Prompts_Selection_Directory {
            get {
                return ResourceManager.GetString("Prompts.Selection.Directory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move UP or DOWN to reveal more options.
        /// </summary>
        internal static string Prompts_Selection_RevealMoreOptions {
            get {
                return ResourceManager.GetString("Prompts.Selection.RevealMoreOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select the Storage Drive to search for the executable/command..
        /// </summary>
        internal static string Prompts_Selection_StorageDrive {
            get {
                return ResourceManager.GetString("Prompts.Selection.StorageDrive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the name of the Command or Executable to search for:.
        /// </summary>
        internal static string Prompts_TextInput_File {
            get {
                return ResourceManager.GetString("Prompts.TextInput.File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The directory to search was not specified..
        /// </summary>
        internal static string ValidationErrors_Directory_NotSpecified {
            get {
                return ResourceManager.GetString("ValidationErrors.Directory.NotSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The storage drive to search was not specified..
        /// </summary>
        internal static string ValidationErrors_Drive_NotSpecified {
            get {
                return ResourceManager.GetString("ValidationErrors.Drive.NotSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File/Command argument must not contain a directory separator character..
        /// </summary>
        internal static string ValidationErrors_File_CannotContainDirectorySeparator {
            get {
                return ResourceManager.GetString("ValidationErrors.File.CannotContainDirectorySeparator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File/Command argument must not be whitespace or empty..
        /// </summary>
        internal static string ValidationErrors_File_EmptyOrWhitespace {
            get {
                return ResourceManager.GetString("ValidationErrors.File.EmptyOrWhitespace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ValidationErrors_File_InvalidMessage {
            get {
                return ResourceManager.GetString("ValidationErrors.File.InvalidMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File/Command argument must be specified..
        /// </summary>
        internal static string ValidationErrors_File_NotSpecified {
            get {
                return ResourceManager.GetString("ValidationErrors.File.NotSpecified", resourceCulture);
            }
        }
    }
}
