//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WhatExec.Cli.Localizations {
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        [EditorBrowsable(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("AlastairLundy.WhatExec.Cli.Localizations.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [EditorBrowsable(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string ValidationErrors_File_NotSpecified {
            get {
                return ResourceManager.GetString("ValidationErrors.File.NotSpecified", resourceCulture);
            }
        }
        
        internal static string ValidationErrors_File_EmptyOrWhitespace {
            get {
                return ResourceManager.GetString("ValidationErrors.File.EmptyOrWhitespace", resourceCulture);
            }
        }
        
        internal static string ValidationErrors_Directory_NotSpecified {
            get {
                return ResourceManager.GetString("ValidationErrors.Directory.NotSpecified", resourceCulture);
            }
        }
        
        internal static string ValidationErrors_Drive_NotSpecified {
            get {
                return ResourceManager.GetString("ValidationErrors.Drive.NotSpecified", resourceCulture);
            }
        }
        
        internal static string Prompts_Selection_StorageDrive {
            get {
                return ResourceManager.GetString("Prompts.Selection.StorageDrive", resourceCulture);
            }
        }
        
        internal static string Prompts_Selection_RevealMoreOptions {
            get {
                return ResourceManager.GetString("Prompts.Selection.RevealMoreOptions", resourceCulture);
            }
        }
        
        internal static string Prompts_Highlights_StorageDrive {
            get {
                return ResourceManager.GetString("Prompts.Highlights.StorageDrive", resourceCulture);
            }
        }
        
        internal static string Prompts_Highlights_Search {
            get {
                return ResourceManager.GetString("Prompts.Highlights.Search", resourceCulture);
            }
        }
        
        internal static string Prompts_Highlights_Directory {
            get {
                return ResourceManager.GetString("Prompts.Highlights.Directory", resourceCulture);
            }
        }
        
        internal static string Prompts_Selection_Directory {
            get {
                return ResourceManager.GetString("Prompts.Selection.Directory", resourceCulture);
            }
        }
        
        internal static string Prompts_TextInput_File {
            get {
                return ResourceManager.GetString("Prompts.TextInput.File", resourceCulture);
            }
        }
        
        internal static string ValidationErrors_File_CannotContainDirectorySeparator {
            get {
                return ResourceManager.GetString("ValidationErrors.File.CannotContainDirectorySeparator", resourceCulture);
            }
        }
        
        internal static string ValidationErrors_File_InvalidMessage {
            get {
                return ResourceManager.GetString("ValidationErrors.File.InvalidMessage", resourceCulture);
            }
        }
        
        internal static string Prompts_CommandInput_AddAnother {
            get {
                return ResourceManager.GetString("Prompts.CommandInput.AddAnother", resourceCulture);
            }
        }
        
        internal static string Exceptions_Commands_Find_Limit_MustBeGreaterThanZero {
            get {
                return ResourceManager.GetString("Exceptions.Commands.Find.Limit.MustBeGreaterThanZero", resourceCulture);
            }
        }
    }
}
